OLLs = {
  "0"  : " // trivial",
  "1"  : "R U2 R2 F R F' U2 R' F R F' // blaze",
  "2"  : "F R U R' U' F' Fw R U R' U' Fw' // dot",
  "3"  : "Fw R U R' U' Fw' U' F R U R' U' F' // !",
  "4"  : "Fw R U R' U' Fw' U F R U R' U' F' // i",
  "5"  : "Rw' U2 R U R' U Rw // anti wide sune",
  "6"  : "Rw U2 R' U' R U' Rw' // anti wide sune",
  "7"  : "Rw U R' U R U2 Rw' // wide sune",
  "8"  : "Rw' U' R U' R' U2 Rw // wide sune",
  "9"  : "R U R' U' R' F R2 U R' U' F'// fish",
  "10"  : "R U R' U R' F R F' R U2 R' // fish",
  "11"  : "Rw' R2 U R' U R U2 R' U M' // lightning",
  "12"  : "F R U R' U' F' U F R U R' U' F' // lightning",
  "13"  : "Rw U' Rw' U' Rw U Rw' F' U F // L",
  "14"  : "R' F R U R' F' R F U' F' // L",
  "15"  : "Rw' U' Rw R' U' R U Rw' U Rw // L",
  "16"  : "Rw U Rw' R U R' U' Rw U' Rw' // L",
  "17"  : "R U R' U R' F R F' U2 R' F R F' // phantom",
  "18"  : "Rw U R' U R U2 Rw2 U' R U' R' U2 Rw // skeleton",
  "19"  : "M U R U R' U' M' R' F R F' // creeper",
  "20"  : "M U R U R' U' M2 U R U' Rw' // guardian",
  "21"  : "R' U' R U' R' U R U' R' U2 R // car",
  "22"  : "R U2 R2 U' R2 U' R2 U2 R // pi",
  "23"  : "R2 D R' U2 R D' R' U2 R' // headlights",
  "24"  : "Rw U R' U' Rw' F R F' // 2 corners",
  "25"  : "R U2 R D R' U2 R D' R2 // 2 corners",
  "26"  : "R' U' R U' R' U2 R // back sune",
  "27"  : "R U R' U R U2 R' // front sune",
  "28"  : "Rw U R' U' M U R U' R' // 2 edges",
  "29"  : "R U R' U' R U' R' F' U' F R U R' // awkward",
  "30"  : "F U R U2 R' U' R U2 R' U' F' // awkward",
  "31"  : "S' L' U' L U Rw U' Rw' Fw // P",
  "32"  : "S R U R' U' R' F R Fw' // P",
  "33"  : "R U R' U' R' F R F' // T",
  "34"  : "R U R2 U' R' F R U R U' F' // C",
  "35"  : "R U2 R2 F R F' R U2 R' // large fish",
  "36"  : "L' U' L U' L' U L U L F' L' F // W",
  "37"  : "F R U' R' U' R U R' F' // large fish",
  "38"  : "R U R' U R U' R' U' R' F R F' // W",
  "39"  : "L F' L' U' L U F U' L' // lightning",
  "40"  : "R' F R U R' U' F' U R // lightning",
  "41"  : "R U R' U R U2 R' F R U R' U' F' // very awkward",
  "42"  : "R' U' R U' R' U2 R F R U R' U' F' // very awkward",
  "43"  : "Fw' L' U' L U Fw // P",
  "44"  : "Fw R U R' U' Fw' // P",
  "45"  : "F R U R' U' F' // T",
  "46"  : "R' U' R' F R F' U R // C bar",
  "47"  : "F' L' U' L U L' U' L U F // 2x fruruf",
  "48"  : "F R U R' U' R U R' U' F' // 2x fruruf",
  "49"  : "Lw U' Lw2 U Lw2 U Lw2 U' Lw // small L",
  "50"  : "Lw' U Lw2 U' Lw2 U' Lw2 U Lw' // small L",
  "51"  : "Fw R U R' U' R U R' U' Fw' // 2x fruruf",
  "52"  : "R U R' U R Dw' R U' R' F' // I",
  "53"  : "Rw' U' R U' R' U R U' R' U2 Rw // 2x wide sune",
  "54"  : "Rw U R' U R U' R' U R U2 Rw' // 2x wide sune",
  "55"  : "R' F U R U' R2 F' R2 U R' U' R // hamburger",
  "56"  : "Rw U Rw' U R U' R' U R U' R' Rw U' Rw' // star",
  "57"  : "R U R' U' M' U R U' Rw' // H"
}