from __future__ import annotations

import importlib
import pkgutil
from typing import TYPE_CHECKING

import cattrs
import numpy as np
from cattrs.strategies import configure_tagged_union
from cattrs.strategies import include_subclasses

from rubiks_cube.beam_search.interface import BeamStep
from rubiks_cube.beam_search.interface import SearchSideChoice
from rubiks_cube.beam_search.interface import Transition
from rubiks_cube.configuration.enumeration import Goal
from rubiks_cube.configuration.enumeration import Variant
from rubiks_cube.move.generator import MoveGenerator
from rubiks_cube.solver.bidirectional import BidirectionalSolver
from rubiks_cube.solver.validators import VALIDATOR_REGISTRY
from rubiks_cube.transform.interface import Transform
from rubiks_cube.transform.pipeline import Pipeline

if TYPE_CHECKING:
    from collections.abc import Sequence


def import_all_submodules(
    package_name: str,
    ignore_submodules: Sequence[str] | None = None,
) -> None:
    """Dynamically import every submodule of 'package_name' so all subclasses are registered."""
    if ignore_submodules is None:
        ignore_submodules = []

    pkg = importlib.import_module(package_name)
    for _, module_name, _ in pkgutil.iter_modules(pkg.__path__):
        if module_name not in ignore_submodules:
            importlib.import_module(f"{package_name}.{module_name}")


def _unstructure_ndarray(arr: np.ndarray) -> dict[str, object]:
    return {"data": arr.tolist(), "dtype": str(arr.dtype), "shape": list(arr.shape)}


def _structure_ndarray(data: dict[str, object], _: type) -> np.ndarray:
    return np.array(data["data"], dtype=np.dtype(data["dtype"])).reshape(data["shape"])  # type: ignore[arg-type]


def _is_ndarray_type(t: object) -> bool:
    if t is np.ndarray:
        return True
    return getattr(t, "__origin__", None) is np.ndarray


def _is_dtype_type(t: object) -> bool:
    if t is np.dtype:
        return True
    return getattr(t, "__origin__", None) is np.dtype


def _unstructure_variant_frozenset_dict(
    d: dict[Variant, frozenset[Variant]] | None,
) -> dict[str, list[str]] | None:
    if d is None:
        return None
    return {k.value: sorted(v.value for v in vs) for k, vs in d.items()}


def _structure_variant_frozenset_dict(
    data: dict[str, list[str]] | None,
) -> dict[Variant, frozenset[Variant]] | None:
    if data is None:
        return None
    return {Variant(k): frozenset(Variant(v) for v in vs) for k, vs in data.items()}


def create_converter() -> cattrs.Converter:
    """Create a cattrs Converter with hooks for numpy arrays and Transform union types."""
    from rubiks_cube.beam_search.solver import CompiledStep  # noqa: PLC0415
    from rubiks_cube.beam_search.solver import CompiledVariant  # noqa: PLC0415

    converter = cattrs.Converter()

    # numpy ndarray: encode as {"data": ..., "dtype": ..., "shape": ...}
    # Both hooks are needed: the class hook covers runtime dispatch; the func hook covers
    # type-hint-based lookup in hooks generated by include_subclasses (NDArray[T] generic
    # aliases have __origin__ == np.ndarray but are not the np.ndarray class itself).
    converter.register_unstructure_hook(np.ndarray, _unstructure_ndarray)
    converter.register_unstructure_hook_func(_is_ndarray_type, _unstructure_ndarray)
    converter.register_structure_hook_func(_is_ndarray_type, _structure_ndarray)

    # np.dtype: encode as its string name
    converter.register_unstructure_hook(np.dtype, str)
    converter.register_unstructure_hook_func(_is_dtype_type, str)
    converter.register_structure_hook_func(_is_dtype_type, lambda data, _: np.dtype(data))

    import_all_submodules(package_name="rubiks_cube.transform")
    include_subclasses(Transform, converter, union_strategy=configure_tagged_union)

    # MoveGenerator: encode as its canonical string "<U, R, ...>"
    converter.register_unstructure_hook(MoveGenerator, str)
    converter.register_structure_hook(MoveGenerator, lambda data, _: MoveGenerator.from_str(data))

    # ---------- beam_search types ----------------------------------------
    # All hooks below use hook_func variants with class-identity predicates to
    # avoid calling attrs.resolve_types on classes that have TYPE_CHECKING-only
    # imports (BoolArray, PatternArray, BeamStep, etc.).

    def _unstructure_transition(t: Transition) -> dict:
        return {
            "search_side": t.search_side.value,
            "generator_map": {k.value: str(v) for k, v in t.generator_map.items()},
            "allowed_variants_by_prev_variant": _unstructure_variant_frozenset_dict(
                t.allowed_variants_by_prev_variant
            ),
            "prev_goal_ref": t.prev_goal_ref,
            "check_contained": t.check_contained,
        }

    def _structure_transition(data: dict, _: type) -> Transition:
        raw_side = data.get("search_side", "prev")
        raw_ref = data.get("prev_goal_ref", data.get("prev_goal_index", -1))
        return Transition(
            search_side=SearchSideChoice(raw_side),
            generator_map={
                Variant(k): MoveGenerator.from_str(v) for k, v in data["generator_map"].items()
            },
            allowed_variants_by_prev_variant=_structure_variant_frozenset_dict(
                data.get("allowed_variants_by_prev_variant")
            ),
            prev_goal_ref=int(raw_ref),
            check_contained=data.get("check_contained", False),
        )

    converter.register_unstructure_hook_func(lambda t: t is Transition, _unstructure_transition)
    converter.register_structure_hook_func(lambda t: t is Transition, _structure_transition)

    def _unstructure_beam_step(step: BeamStep) -> dict:
        return {
            "goal": step.goal.value,
            "variants": [v.value for v in step.variants],
            "transition": converter.unstructure(step.transition),
            "max_search_depth": step.max_search_depth,
            "max_solutions": step.max_solutions,
        }

    def _structure_beam_step(data: dict, _: type) -> BeamStep:
        return BeamStep(
            goal=Goal(data["goal"]),
            variants=[Variant(v) for v in data["variants"]],
            transition=converter.structure(data["transition"], Transition),
            max_search_depth=data.get("max_search_depth", 10),
            max_solutions=data.get("max_solutions", 1),
        )

    converter.register_unstructure_hook_func(lambda t: t is BeamStep, _unstructure_beam_step)
    converter.register_structure_hook_func(lambda t: t is BeamStep, _structure_beam_step)

    def _unstructure_solver(solver: BidirectionalSolver) -> dict:
        return {
            "pipeline": converter.unstructure(solver.pipeline),
            "actions": {k: _unstructure_ndarray(v) for k, v in solver.actions.items()},
            "pattern": _unstructure_ndarray(solver.pattern),
            "adj_matrix": _unstructure_ndarray(solver.adj_matrix),
            "validator_key": solver.validator_key,
        }

    def _structure_solver(data: dict, _: type) -> BidirectionalSolver:
        validator_key = data.get("validator_key")
        if validator_key is not None and validator_key not in VALIDATOR_REGISTRY:
            raise ValueError(
                f"Unknown validator_key {validator_key!r} in serialized solver data. "
                f"Available keys: {sorted(VALIDATOR_REGISTRY)}"
            )
        return BidirectionalSolver(
            pipeline=converter.structure(data["pipeline"], Pipeline),
            actions={k: _structure_ndarray(v, type(None)) for k, v in data["actions"].items()},
            pattern=_structure_ndarray(data["pattern"], type(None)),
            adj_matrix=_structure_ndarray(data["adj_matrix"], type(None)),
            validator_key=validator_key,
        )

    converter.register_unstructure_hook_func(
        lambda t: t is BidirectionalSolver, _unstructure_solver
    )
    converter.register_structure_hook_func(lambda t: t is BidirectionalSolver, _structure_solver)

    def _unstructure_compiled_variant(ctx: CompiledVariant) -> dict:
        return {
            "goal": ctx.goal.value,
            "variant": ctx.variant.value,
            "step": converter.unstructure(ctx.step),
            "solver": converter.unstructure(ctx.solver),
            "pattern": _unstructure_ndarray(ctx.pattern),
        }

    def _structure_compiled_variant(data: dict, _: type) -> CompiledVariant:
        return CompiledVariant(
            goal=Goal(data["goal"]),
            variant=Variant(data["variant"]),
            step=converter.structure(data["step"], BeamStep),
            solver=converter.structure(data["solver"], BidirectionalSolver),
            pattern=_structure_ndarray(data["pattern"], type(None)),
        )

    converter.register_unstructure_hook_func(
        lambda t: t is CompiledVariant, _unstructure_compiled_variant
    )
    converter.register_structure_hook_func(
        lambda t: t is CompiledVariant, _structure_compiled_variant
    )

    def _unstructure_compiled_step(so: CompiledStep) -> dict:
        return {
            "step": converter.unstructure(so.step),
            "contexts_by_generator": {
                "|".join(sorted(k)): [converter.unstructure(ctx) for ctx in ctxs]
                for k, ctxs in so.contexts_by_generator.items()
            },
            "allowed_prev_variants_by_variant": _unstructure_variant_frozenset_dict(
                so.allowed_prev_variants_by_variant
            ),
        }

    def _structure_compiled_step(data: dict, _: type) -> CompiledStep:
        return CompiledStep(
            step=converter.structure(data["step"], BeamStep),
            contexts_by_generator={
                frozenset(k.split("|")) if k else frozenset(): [
                    converter.structure(ctx, CompiledVariant) for ctx in ctxs
                ]
                for k, ctxs in data["contexts_by_generator"].items()
            },
            allowed_prev_variants_by_variant=_structure_variant_frozenset_dict(
                data.get("allowed_prev_variants_by_variant")
            ),
        )

    converter.register_unstructure_hook_func(
        lambda t: t is CompiledStep, _unstructure_compiled_step
    )
    converter.register_structure_hook_func(lambda t: t is CompiledStep, _structure_compiled_step)

    return converter
