from __future__ import annotations

import importlib
import pkgutil
from typing import Sequence

import cattrs
import numpy as np
from cattrs.strategies import configure_tagged_union
from cattrs.strategies import include_subclasses

from rubiks_cube.transform.interface import Transform


def import_all_submodules(
    package_name: str,
    ignore_submodules: Sequence[str] | None = None,
) -> None:
    """Dynamically import every submodule of 'package_name' so all subclasses are registered."""
    if ignore_submodules is None:
        ignore_submodules = []

    pkg = importlib.import_module(package_name)
    for _, module_name, _ in pkgutil.iter_modules(pkg.__path__):
        if module_name not in ignore_submodules:
            importlib.import_module(f"{package_name}.{module_name}")


def _unstructure_ndarray(arr: np.ndarray) -> dict[str, object]:
    return {"data": arr.tolist(), "dtype": str(arr.dtype), "shape": list(arr.shape)}


def _structure_ndarray(data: dict[str, object], _: type) -> np.ndarray:
    return np.array(data["data"], dtype=np.dtype(data["dtype"])).reshape(data["shape"])  # type: ignore[arg-type]


def _is_ndarray_type(t: object) -> bool:
    if t is np.ndarray:
        return True
    return getattr(t, "__origin__", None) is np.ndarray


def _is_dtype_type(t: object) -> bool:
    if t is np.dtype:
        return True
    return getattr(t, "__origin__", None) is np.dtype


def create_converter() -> cattrs.Converter:
    """Create a cattrs Converter with hooks for numpy arrays and Transform union types."""

    converter = cattrs.Converter()

    # numpy ndarray: encode as {"data": ..., "dtype": ..., "shape": ...}
    # Both hooks are needed: the class hook covers runtime dispatch; the func hook covers
    # type-hint-based lookup in hooks generated by include_subclasses (NDArray[T] generic
    # aliases have __origin__ == np.ndarray but are not the np.ndarray class itself).
    converter.register_unstructure_hook(np.ndarray, _unstructure_ndarray)
    converter.register_unstructure_hook_func(_is_ndarray_type, _unstructure_ndarray)
    converter.register_structure_hook_func(_is_ndarray_type, _structure_ndarray)

    # np.dtype: encode as its string name
    converter.register_unstructure_hook(np.dtype, str)
    converter.register_unstructure_hook_func(_is_dtype_type, str)
    converter.register_structure_hook_func(_is_dtype_type, lambda data, _: np.dtype(data))

    import_all_submodules(package_name="rubiks_cube.transform")
    include_subclasses(Transform, converter, union_strategy=configure_tagged_union)

    return converter
