from __future__ import annotations

from typing import Final

IDENTITY_ROTATION_STATE: Final[str] = "UF"

ROTATION_SOLUTIONS: Final[dict[str, list[str]]] = {
    "UF": [],
    "UL": ["y'"],
    "UB": ["y2"],
    "UR": ["y"],
    "FU": ["x", "y2"],
    "FL": ["x", "y'"],
    "FD": ["x"],
    "FR": ["x", "y"],
    "RU": ["z'", "y'"],
    "RF": ["z'"],
    "RD": ["z'", "y"],
    "RB": ["z'", "y2"],
    "BU": ["x'"],
    "BL": ["x'", "y'"],
    "BD": ["x'", "y2"],
    "BR": ["x'", "y"],
    "LU": ["z", "y"],
    "LF": ["z"],
    "LD": ["z", "y'"],
    "LB": ["z", "y2"],
    "DF": ["z2"],
    "DL": ["x2", "y'"],
    "DB": ["x2"],
    "DR": ["x2", "y"],
}

ROTATION_TRANSITION_TABLE: Final[dict[str, dict[str, str]]] = {
    "x": {
        "UF": "FD",
        "UL": "LD",
        "UB": "BD",
        "UR": "RD",
        "FU": "UB",
        "FL": "LB",
        "FD": "DB",
        "FR": "RB",
        "RU": "UL",
        "RF": "FL",
        "RD": "DL",
        "RB": "BL",
        "BU": "UF",
        "BL": "LF",
        "BD": "DF",
        "BR": "RF",
        "LU": "UR",
        "LF": "FR",
        "LD": "DR",
        "LB": "BR",
        "DF": "FU",
        "DL": "LU",
        "DB": "BU",
        "DR": "RU",
    },
    "x'": {
        "UF": "BU",
        "UL": "RU",
        "UB": "FU",
        "UR": "LU",
        "FU": "DF",
        "FL": "RF",
        "FD": "UF",
        "FR": "LF",
        "RU": "DR",
        "RF": "BR",
        "RD": "UR",
        "RB": "FR",
        "BU": "DB",
        "BL": "RB",
        "BD": "UB",
        "BR": "LB",
        "LU": "DL",
        "LF": "BL",
        "LD": "UL",
        "LB": "FL",
        "DF": "BD",
        "DL": "RD",
        "DB": "FD",
        "DR": "LD",
    },
    "x2": {
        "UF": "DB",
        "UL": "DR",
        "UB": "DF",
        "UR": "DL",
        "FU": "BD",
        "FL": "BR",
        "FD": "BU",
        "FR": "BL",
        "RU": "LD",
        "RF": "LB",
        "RD": "LU",
        "RB": "LF",
        "BU": "FD",
        "BL": "FR",
        "BD": "FU",
        "BR": "FL",
        "LU": "RD",
        "LF": "RB",
        "LD": "RU",
        "LB": "RF",
        "DF": "UB",
        "DL": "UR",
        "DB": "UF",
        "DR": "UL",
    },
    "y": {
        "UF": "UR",
        "UL": "UF",
        "UB": "UL",
        "UR": "UB",
        "FU": "FL",
        "FL": "FD",
        "FD": "FR",
        "FR": "FU",
        "RU": "RF",
        "RF": "RD",
        "RD": "RB",
        "RB": "RU",
        "BU": "BR",
        "BL": "BU",
        "BD": "BL",
        "BR": "BD",
        "LU": "LB",
        "LF": "LU",
        "LD": "LF",
        "LB": "LD",
        "DF": "DL",
        "DL": "DB",
        "DB": "DR",
        "DR": "DF",
    },
    "y'": {
        "UF": "UL",
        "UL": "UB",
        "UB": "UR",
        "UR": "UF",
        "FU": "FR",
        "FL": "FU",
        "FD": "FL",
        "FR": "FD",
        "RU": "RB",
        "RF": "RU",
        "RD": "RF",
        "RB": "RD",
        "BU": "BL",
        "BL": "BD",
        "BD": "BR",
        "BR": "BU",
        "LU": "LF",
        "LF": "LD",
        "LD": "LB",
        "LB": "LU",
        "DF": "DR",
        "DL": "DF",
        "DB": "DL",
        "DR": "DB",
    },
    "y2": {
        "UF": "UB",
        "UL": "UR",
        "UB": "UF",
        "UR": "UL",
        "FU": "FD",
        "FL": "FR",
        "FD": "FU",
        "FR": "FL",
        "RU": "RD",
        "RF": "RB",
        "RD": "RU",
        "RB": "RF",
        "BU": "BD",
        "BL": "BR",
        "BD": "BU",
        "BR": "BL",
        "LU": "LD",
        "LF": "LB",
        "LD": "LU",
        "LB": "LF",
        "DF": "DB",
        "DL": "DR",
        "DB": "DF",
        "DR": "DL",
    },
    "z": {
        "UF": "LF",
        "UL": "BL",
        "UB": "RB",
        "UR": "FR",
        "FU": "RU",
        "FL": "UL",
        "FD": "LD",
        "FR": "DR",
        "RU": "BU",
        "RF": "UF",
        "RD": "FD",
        "RB": "DB",
        "BU": "LU",
        "BL": "DL",
        "BD": "RD",
        "BR": "UR",
        "LU": "FU",
        "LF": "DF",
        "LD": "BD",
        "LB": "UB",
        "DF": "RF",
        "DL": "FL",
        "DB": "LB",
        "DR": "BR",
    },
    "z'": {
        "UF": "RF",
        "UL": "FL",
        "UB": "LB",
        "UR": "BR",
        "FU": "LU",
        "FL": "DL",
        "FD": "RD",
        "FR": "UR",
        "RU": "FU",
        "RF": "DF",
        "RD": "BD",
        "RB": "UB",
        "BU": "RU",
        "BL": "UL",
        "BD": "LD",
        "BR": "DR",
        "LU": "BU",
        "LF": "UF",
        "LD": "FD",
        "LB": "DB",
        "DF": "LF",
        "DL": "BL",
        "DB": "RB",
        "DR": "FR",
    },
    "z2": {
        "UF": "DF",
        "UL": "DL",
        "UB": "DB",
        "UR": "DR",
        "FU": "BU",
        "FL": "BL",
        "FD": "BD",
        "FR": "BR",
        "RU": "LU",
        "RF": "LF",
        "RD": "LD",
        "RB": "LB",
        "BU": "FU",
        "BL": "FL",
        "BD": "FD",
        "BR": "FR",
        "LU": "RU",
        "LF": "RF",
        "LD": "RD",
        "LB": "RB",
        "DF": "UF",
        "DL": "UL",
        "DB": "UB",
        "DR": "UR",
    },
}
