"""Unit tests for Schreier-Sims algorithm."""

from __future__ import annotations

from rubiks_cube.move.generator import MoveGenerator
from rubiks_cube.move.meta import MoveMeta
from rubiks_cube.move.sequence import MoveSequence
from rubiks_cube.representation import get_rubiks_cube_permutation
from rubiks_cube.solver.schreier_sims import is_solvable


class TestIsSolvable:
    move_meta: MoveMeta = MoveMeta.from_cube_size(3)

    def test_identity_with_empty_generator(self) -> None:
        """Test that identity is solvable with empty generator."""
        identity = self.move_meta.get_identity_permutation()
        generator = MoveGenerator.from_str("<>")
        assert is_solvable(identity, generator, cube_size=self.move_meta.cube_size)

    def test_simple_solvable_case(self) -> None:
        """Test that a permutation generated by moves is solvable with those moves."""
        generator = MoveGenerator.from_str("<R2, U2>")
        scramble = MoveSequence.from_str("R2 U2 R2 U2")

        perm = get_rubiks_cube_permutation(scramble, move_meta=self.move_meta)
        assert is_solvable(perm, generator, self.move_meta.cube_size)

    def test_sequence_not_solvable_with_subset(self) -> None:
        """Test that a sequence using F is not solvable with only R2, U2."""
        generator = MoveGenerator.from_str("<R2, U2>")
        scramble = MoveSequence.from_str("F")
        perm = get_rubiks_cube_permutation(scramble, move_meta=self.move_meta)
        assert not is_solvable(perm, generator, self.move_meta.cube_size)
