"""Unit tests for Schreier-Sims algorithm."""

from __future__ import annotations

from rubiks_cube.move.generator import MoveGenerator
from rubiks_cube.move.sequence import MoveSequence
from rubiks_cube.representation import get_rubiks_cube_state
from rubiks_cube.representation.permutation import get_identity_permutation
from rubiks_cube.solver.schreier_sims import get_group_order
from rubiks_cube.solver.schreier_sims import is_solvable


class TestIsSolvable:
    def test_identity_with_empty_generator(self) -> None:
        """Test that identity is solvable with empty generator."""
        identity = get_identity_permutation(cube_size=3)
        generator = MoveGenerator("<>")
        assert is_solvable(identity, generator, cube_size=3)

    def test_simple_solvable_case(self) -> None:
        """Test that a permutation generated by moves is solvable with those moves."""
        generator = MoveGenerator("<R2, U2>")
        scramble = MoveSequence("R2 U2 R2 U2")
        perm = get_rubiks_cube_state(scramble, cube_size=3)
        assert is_solvable(perm, generator, cube_size=3)

    def test_sequence_not_solvable_with_subset(self) -> None:
        """Test that a sequence using F is not solvable with only R2, U2."""
        generator = MoveGenerator("<R2, U2>")
        scramble = MoveSequence("F")
        perm = get_rubiks_cube_state(scramble, cube_size=3)
        assert not is_solvable(perm, generator, cube_size=3)


class TestGroupOrder:
    def test_single_move_order(self) -> None:
        """Test order of group generated by single move."""
        generator = MoveGenerator("<R>")
        order = get_group_order(generator, cube_size=3)
        # R has order 4 (R^4 = I), so <R> should have 4 elements
        assert order == 4

    def test_r2_move_order(self) -> None:
        """Test order of R2 move."""
        generator = MoveGenerator("<R2>")
        order = get_group_order(generator, cube_size=3)
        # R2 has order 2, so <R2> has 2 elements
        assert order == 2
